# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jpirsch <jpirsch@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/10/01 18:06:45 by jpirsch           #+#    #+#              #
#    Updated: 2015/10/01 18:14:44 by jpirsch          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

export FLAGS	=	-Wall -Wextra -Werror
NAME			=	mod1
SRC_DIR			=	./sources

all:
	make -C $(SRC_DIR)

clean:
	make -C $(SRC_DIR) clean

fclean: clean
	make -C $(SRC_DIR) fclean

re: fclean all
